version: "3"

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: catalog_database
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  iceberg-rest-catalog-rs:
    image: alpine:latest
    container_name: iceberg-rest-catalog-rs
    build: 
      context: .
    depends_on:
      - postgres
      - minio
    networks:
      iceberg_net:
    entrypoint: |
      sh -c "apk add --no-cache curl && curl -L -o /usr/local/bin/iceberg-rest-catalog-rs  https://github.com/hansetag/iceberg-catalog/releases/download/v0.3.0/iceberg-catalog-aarch64-unknown-linux-musl.tar.gz && chmod +x /usr/local/bin/iceberg-rest-catalog-rs && /usr/local/bin/iceberg-rest-catalog-rs"
    ports:
      - 8060:8060
    environment:
      - ICEBERG_REST__BASE_URI=http://localhost:8060
      - ICEBERG_REST__LISTEN_PORT=8060
      - AWS_SECRET_ACCESS_KEY=password
      - ICEBERG_REST__DEFAULT_PROJECT_ID="00000000-0000-0000-0000-000000000000"
      - ICEBERG_REST__PG_DATABASE_URL_READ="postgres://user:pass@localhost:5432/catalog_database"
      - ICEBERG_REST__PG_DATABASE_URL_WRITE="postgres://user:pass@localhost:5432/catalog_database"
      - ICEBERG_REST__PG_ENCRYPTION_KEY="MySecretEncryptionKeyThatIBetterNotLoose"
      - AWS_REGION=us-east-1

  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    build: spark/
    networks:
      iceberg_net:
    depends_on:
      - iceberg-rest-catalog-rs
      - minio
    volumes:
      - ./warehouse:/home/iceberg/warehouse
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    ports:
      - 8080:8080
    # entrypoint: |
    #   sh -c "\
    #   apk add --no-cache curl && \
    #   curl -L -o /usr/local/bin/iceberg-rest-catalog-rs  https://github.com/hansetag/iceberg-catalog/releases/download/v0.3.0/iceberg-catalog-aarch64-unknown-linux-musl.tar.gz && \
    #   chmod +x /usr/local/bin/iceberg-rest-catalog-rs && \
    #   /usr/local/bin/iceberg-rest-catalog-rs"

networks:
  iceberg_net:
